Various misc. improvements to ProxySQL automation
- ProxySQL data dir is backed up on package upgrades to allow for easy
rollbacks
- check-query-digest print statement now has a timestamp to allow it to
be picked up by GUTS
- Consul health checks can now be triggered to fail via the creation of
a file
- Various ProxySQL configuration parameters have been exposed via chef
attributes

Signed-off-by: Mike Boruta <mboruta1@bloomberg.net>

diff --git a/chef/cookbooks/bcpc/templates/default/consul/proxysql-check-helper.erb b/chef/cookbooks/bcpc/templates/default/consul/proxysql-check-helper.erb
--- a/chef/cookbooks/bcpc/templates/default/consul/proxysql-check-helper.erb
+++ b/chef/cookbooks/bcpc/templates/default/consul/proxysql-check-helper.erb
@@ -16,6 +16,11 @@
 
 set -e
 
+# Check whether the maintenance flag is set; if so fail the health check
+if [ -f "<%= node['bcpc']['proxysql']['datadir'] %>/files/maintenance" ]; then
+    exit 1
+fi
+
 # Check connectivity to ProxySQL's admin interface
 mysqladmin status \
     --connect-timeout 10 \
